---
version: "0.2"
language: en_US
caseSensitive: false
dictionaries:
  - en_US
  - companies
  - softwareTerms
  - misc
  - go
  - python
  - bash
words:
  - cpus
  - rootdisk
  - examplepassword
  - virtualmachine
  - cloudinit
  - kubeconfig
  - Terragrunt
  - boop
  - taskfile
  - taskfiles
  - Taskfile
