---
  # yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
  name: "Label Sync"

  on:
    workflow_dispatch:
    push:
      branches: ["main"]
      paths: [".github/labels.yaml"]
    schedule:
      - cron: "0 0 * * *"

  permissions:
    issues: write
    contents: read

  jobs:
    label-sync:
      name: Label Sync
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            sparse-checkout: .github/labels.yaml

        - name: Sync Labels
          uses: EndBug/label-sync@v2
          with:
            request-token: ${{ secrets.GITHUB_TOKEN }}
            config-file: .github/labels.yaml
            delete-other-labels: true
